name: ZcaTool Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        runtime: ['win-x64', 'linux-x64', 'osx-x64']
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Release build (${{ matrix.runtime }})
        run:  dotnet publish -c Release -f netcoreapp3.0 -r ${{ matrix.runtime }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ZcaTool-${{ matrix.runtime }}
          path: ZcaTool/bin/Release/netcoreapp3.0/${{ matrix.runtime }}/publish/